### ISSUE TITLE
@jlaine thanks but how to use hq-interop？

### ISSUE THREAD

**Issue by xtuyaowu** [aiortc/aioquic#266] opened 2022-02-10 13:47 UTC
@jlaine thanks but how to use hq-interop？
i change from .applicationProtocols("http/0.9").build(); to .applicationProtocols("http/3.0").build();
but still fail
javax.net.ssl.SSLHandshakeException: QUICHE_ERR_TLS_FAIL: error:10000133:SSL routines:OPENSSL_internal:NO_APPLICATION_PROTOCOL

_Originally posted by @xtuyaowu in https://github.com/aiortc/aioquic/issues/264#issuecomment-1033291555_

**Comment by jlaine** [comment] 2022-02-10 13:58
Duplicate of #264

**Closed by jlaine** 2022-02-10 13:58 UTC

**Comment by xtuyaowu** [comment] 2022-02-20 00:26
have solve both side should use same protocol 
thanks
