### ISSUE TITLE
comunication with rust QUIC server.

### ISSUE THREAD

**Issue by devvyn-mark-qtc** [aiortc/aioquic#320] opened 2022-08-09 10:44 UTC
Hello,

I've tried to make connection to rust QUIC server [quinn](https://github.com/quinn-rs/quinn) (ver 0.8.0),  the server always returns: `code 0x178, reason peer doesn't support any known protocol`. I believe the error comes from rustls - [rust_tsl_implementation_line_171](https://rust.velas.com/src/rustls/server/hs.rs.html#171). 

It looks like tls implementation from this library is messing with ALPN. I've tried all of H0, H3 and also others.
Or the there is sth wrong with TLS version, as with TLS1.2 it said "reason peer is incompatible: Expecting QUIC connection, but client does not support TLSv1_3", but with TLS1.3: "peer doesn't support any known protocol"

I couldnt connect to my local rust quic server using any of examples in this repo, nor with my own code:
`
quic_connection = QuicConnection(
        configuration=configuration, session_ticket_handler=save_session_ticket
    )
    
    host, port = urls[0].rsplit(":", 1)
    
    addr = (host, int(port))
    print(addr)
    
    loop = asyncio.get_event_loop()
    local_host = "::"
    
    sock = socket.socket(socket.AF_INET6, socket.SOCK_DGRAM) 
    sock.setsockopt(socket.IPPROTO_IPV6, socket.IPV6_V6ONLY, 0)
    sock.bind((local_host, local_port, 0, 0))
    
    # connect
    transport, protocol = await loop.create_datagram_endpoint(
        lambda: QuicConnectionProtocol(quic_connection, stream_handler=None),
        sock=sock,
    )
    
    protocol.connect(addr)
    await protocol.wait_connected()
`

Do you have any clue how to make it working?

Greetings

**Comment by devvyn-mark-qtc** [comment] 2022-08-15 08:02
bump, as it wasnt visible before.

**Comment by pyfisch** [comment] 2022-08-16 07:22
Hi,

I investigated this and it isn't an issue with aioquic, rather quinn only supports the `hq-29` protocol  (from the RFC draft). To connect with aioquic you need to specify this ALPN value. For example you can run the client as `python examples/http3_client.py --ca-certs tests/pycacert.pem --legacy-http https://localhost:4433`, the `--legacy-http` option enables the `hq-29` application protocol.

**Comment by jlaine** [comment] 2022-09-05 12:58
I'm going to close this issue as the problem is on the quinn side. However be aware that draft protocol versions are going to disappear from the aioquic codebase sooner or later.

**Closed by jlaine** 2022-09-05 12:58 UTC
