### ISSUE TITLE
Add support to send whole file using "--data" argument

### ISSUE THREAD

**Issue by Karthikdasari0423** [aiortc/aioquic#305] opened 2022-07-13 04:00 UTC
Hai, @jlaine 

I am trying to upload file using aioquic(using below command) and not able to get how to do 
and instead getting file with data as "Method Not Allowed" while using below command

I didn't made any changes to http3_client.py or http3_server.py

(python3 /root/aioquic/examples/http3_client.py --ca-certs /root/aioquic/tests/pycacert.pem -v https://1.2.3.4:4433/new.pdf --output-dir /tmp/ --data new.pdf)

Is this expected behaviour or am I missing anything.

Do i need to place the file which i wanted to upload under any specific folder like /aioquic/examples/

Could you please help me to send file using aioquic http3_client.py "--data" argument.

Looking forward for your reply

Thank you.

**Comment by jlaine** [comment] 2022-07-17 14:35
Seems to be a duplicate of discussion #306

**Closed by jlaine** 2022-07-17 14:35 UTC

**Comment by Karthikdasari0423** [comment] 2022-07-17 14:44
yes yes
it is duplicate of https://github.com/aiortc/aioquic/discussions/306 and i am the person who wrote both

Hope you will answer one of the request.

**Comment by Karthikdasari0423** [comment] 2022-07-17 15:18
Thank you for answering discussion. and providing some good amount of idea to work on it.
